version: '3'

services:
  web:
    image: ghcr.io/surreymagpie/nginx-php:latest
    ports:
      - 8000:80
    environment:
      - WEBROOT=web
    volumes:
      - .:/var/www/html:Z,rw
      - $HOME/.ssh:/root/.ssh:Z,rw

  db:
    image: docker.io/library/mariadb:10.6.16
    environment:
      - MYSQL_USER=drupal10
      - MYSQL_PASSWORD=drupal10
      - MYSQL_DATABASE=drupal10
      - MYSQL_ROOT_PASSWORD=drupal10
    volumes:
      - d10-dbdata:/var/libmysql

  d7:
    image: ghcr.io/surreymagpie/nginx-php:latest
    ports:
      - 8001:80
    volumes:
      - ../d7-cornerhouse:/var/www/html:Z,rw
      - $HOME/.ssh:/root/.ssh:Z,rw

  legacy:
    image: docker.io/library/mariadb:10.6.16
    environment:
      - MYSQL_USER=drupal7
      - MYSQL_PASSWORD=drupal7
      - MYSQL_DATABASE=drupal7
      - MYSQL_ROOT_PASSWORD=drupal7
    volumes:
      - d7-dbdata:/var/lib/mysql

volumes:
  d10-dbdata:
  d7-dbdata:

